<?php
/**
 * Módulo admin: expositores do 2º Encontro de Ceramistas.
 * Instalar: docker compose exec -u www-data app php system/instalar_modulo.php ceramistas_expositores
 */
return array(
	'id' => 'ceramistas_expositores',
	'titulo' => 'Expositores do encontro de ceramistas',
	'doc' => 'docs/sql-ceramistas.md',
	'schema_sql' => dirname(__DIR__, 2).'/sql/ceramistas_schema.sql',
	'forms' => array(
		array(
			'arquivo_def' => 'expositores_fotos',
			'tabela' => 'expositores_fotos',
			'nome' => 'Fotos dos expositores',
			'legenda' => 'Galeria de fotos do expositor',
			'menu' => '',
			'posinsert' => 'auto_posinsert_expositores_fotos',
			'posupdate' => 'auto_posupdate_expositores_fotos',
			'sql_ordem' => "echo 'ordem ASC, id ASC';",
			'campos' => array(
				array(
					'nome' => 'Expositor',
					'campo_tabela' => 'expositor_id',
					'type' => 'select',
					'caracteristica' => 2,
					'join_tabela' => 'expositores',
					'join_chave_extrangeira' => 'id',
					'join_campo_exibido' => 'nome',
					'exb_listagem' => 1,
					'validacao' => 'select',
					'secao' => 'Foto',
					'ordem' => 1,
				),
				array(
					'nome' => 'Arquivo',
					'campo_tabela' => 'arquivo',
					'type' => 'text',
					'exb_listagem' => 1,
					'mapear_componente' => 'upload_imagem_padrao',
					'parametros_componente' => "w=1200\r\nh=1200\r\nview=200",
					'secao' => 'Foto',
					'ordem' => 2,
				),
				array(
					'nome' => 'Legenda',
					'campo_tabela' => 'legenda',
					'type' => 'text',
					'class' => ' gWidth',
					'exb_listagem' => 1,
					'secao' => 'Foto',
					'ordem' => 3,
				),
				array(
					'nome' => 'Ordem',
					'campo_tabela' => 'ordem',
					'type' => 'text',
					'exb_listagem' => 1,
					'secao' => 'Foto',
					'ordem' => 4,
				),
				array(
					'nome' => 'Destaque',
					'campo_tabela' => 'destaque',
					'type' => 'select',
					'valor' => 'Não,Sim',
					'exb_listagem' => 1,
					'secao' => 'Foto',
					'ordem' => 5,
				),
			),
		),
		array(
			'arquivo_def' => 'expositores',
			'tabela' => 'expositores',
			'nome' => 'Expositores',
			'legenda' => 'Cadastro dos expositores do encontro de ceramistas',
			'menu' => 'Encontro',
			'link' => 'expositores',
			'preinsert' => 'auto_preinsert_expositores',
			'preupdate' => 'auto_preupdate_expositores',
			'sql_ordem' => "echo 'grupo ASC, ordem ASC, nome ASC';",
			'bt_adicional' => 'expositoresgaleria',
			'relacionados' => array(
				array(
					'botao' => 'Galeria',
					'chave_primaria' => 'id',
					'form' => 'expositores_fotos',
					'chave_estrangeira' => 'expositor_id',
				),
			),
			'campos' => array(
				array('nome' => 'Nome', 'campo_tabela' => 'nome', 'type' => 'text', 'class' => ' gWidth', 'exb_listagem' => 1, 'exb_filtro' => 1, 'validacao' => 'text', 'secao' => 'Identificação', 'ordem' => 1),
				array('nome' => 'Slug (URL)', 'campo_tabela' => 'slug', 'type' => 'text', 'class' => ' gWidth', 'exb_listagem' => 1, 'secao' => 'Identificação', 'ordem' => 2),
				array(
					'nome' => 'Grupo',
					'campo_tabela' => 'grupo',
					'type' => 'select',
					'caracteristica' => 2,
					'join_tabela' => 'expositores_grupos',
					'join_chave_extrangeira' => 'id',
					'join_campo_exibido' => 'nome',
					'exb_listagem' => 1,
					'exb_filtro' => 1,
					'validacao' => 'select',
					'secao' => 'Identificação',
					'ordem' => 3,
				),
				array('nome' => 'Categoria', 'campo_tabela' => 'categoria', 'type' => 'text', 'class' => ' gWidth', 'exb_listagem' => 1, 'exb_filtro' => 1, 'secao' => 'Identificação', 'ordem' => 4),
				array('nome' => 'Resumo', 'campo_tabela' => 'resumo', 'type' => 'textarea', 'class' => ' ggWidth', 'secao' => 'Textos', 'ordem' => 5),
				array('nome' => 'Descrição', 'campo_tabela' => 'descricao', 'type' => 'textarea', 'class' => ' ggWidth', 'validacao' => 'text', 'secao' => 'Textos', 'ordem' => 6),
				array(
					'nome' => 'Logo',
					'campo_tabela' => 'logo',
					'type' => 'text',
					'mapear_componente' => 'upload_imagem_padrao',
					'parametros_componente' => "w=800\r\nh=800\r\nview=160",
					'secao' => 'Imagens',
					'ordem' => 7,
				),
				array(
					'nome' => 'Foto de destaque',
					'campo_tabela' => 'foto_destaque',
					'type' => 'text',
					'exb_listagem' => 1,
					'mapear_componente' => 'upload_imagem_padrao',
					'parametros_componente' => "w=1200\r\nh=1200\r\nview=200",
					'secao' => 'Imagens',
					'ordem' => 8,
				),
				array('nome' => 'Instagram', 'campo_tabela' => 'instagram', 'type' => 'text', 'class' => ' gWidth', 'secao' => 'Contato', 'ordem' => 9),
				array('nome' => 'WhatsApp', 'campo_tabela' => 'whatsapp', 'type' => 'text', 'secao' => 'Contato', 'ordem' => 10),
				array('nome' => 'Ordem', 'campo_tabela' => 'ordem', 'type' => 'text', 'exb_listagem' => 1, 'secao' => 'Publicação', 'ordem' => 11),
				array(
					'nome' => 'Ativo no site',
					'campo_tabela' => 'ativo',
					'type' => 'select',
					'valor' => 'Não,Sim',
					'exb_listagem' => 1,
					'exb_filtro' => 1,
					'secao' => 'Publicação',
					'ordem' => 12,
				),
			),
		),
	),
);
