<?php
/**
 * Módulo admin: programação do 2º Encontro de Ceramistas.
 * Instalar: docker compose exec -u www-data app php system/instalar_modulo.php ceramistas_programacao
 */
return array(
	'id' => 'ceramistas_programacao',
	'titulo' => 'Programação do encontro de ceramistas',
	'doc' => 'docs/sql-ceramistas.md',
	'schema_sql' => dirname(__DIR__, 2).'/sql/ceramistas_schema.sql',
	'forms' => array(
		array(
			'arquivo_def' => 'programacao',
			'tabela' => 'programacao',
			'nome' => 'Programação',
			'legenda' => 'Agenda dos dois dias do encontro',
			'menu' => 'Encontro',
			'link' => 'programacao',
			'preinsert' => 'auto_preinsert_programacao',
			'preupdate' => 'auto_preupdate_programacao',
			'sql_ordem' => "echo 'dia ASC, hora_inicio ASC, ordem ASC';",
			'campos' => array(
				array('nome' => 'Título', 'campo_tabela' => 'titulo', 'type' => 'text', 'class' => ' gWidth', 'exb_listagem' => 1, 'exb_filtro' => 1, 'validacao' => 'text', 'secao' => 'Atividade', 'ordem' => 1),
				array('nome' => 'Descrição', 'campo_tabela' => 'descricao', 'type' => 'textarea', 'class' => ' ggWidth', 'secao' => 'Atividade', 'ordem' => 2),
				array(
					'nome' => 'Categoria',
					'campo_tabela' => 'categoria',
					'type' => 'select',
					'caracteristica' => 2,
					'join_tabela' => 'programacao_categorias',
					'join_chave_extrangeira' => 'id',
					'join_campo_exibido' => 'nome',
					'exb_listagem' => 1,
					'exb_filtro' => 1,
					'validacao' => 'select',
					'secao' => 'Atividade',
					'ordem' => 3,
				),
				array(
					'nome' => 'Ícone',
					'campo_tabela' => 'icone',
					'type' => 'select',
					'caracteristica' => 2,
					'join_tabela' => 'programacao_icones',
					'join_chave_extrangeira' => 'id',
					'join_campo_exibido' => 'nome',
					'exb_listagem' => 0,
					'validacao' => 'select',
					'secao' => 'Atividade',
					'ordem' => 4,
				),
				array(
					'nome' => 'Dia',
					'campo_tabela' => 'dia',
					'type' => 'text',
					'mascara' => 'data',
					'exb_listagem' => 1,
					'exb_filtro' => 1,
					'validacao' => 'text',
					'secao' => 'Horário',
					'ordem' => 5,
				),
				array(
					'nome' => 'Início',
					'campo_tabela' => 'hora_inicio',
					'type' => 'text',
					'mascara' => 'hora',
					'exb_listagem' => 1,
					'validacao' => 'text',
					'funcao_exibicao' => 'auto_exibe_hora',
					'secao' => 'Horário',
					'ordem' => 6,
				),
				array(
					'nome' => 'Fim',
					'campo_tabela' => 'hora_fim',
					'type' => 'text',
					'mascara' => 'hora',
					'exb_listagem' => 1,
					'funcao_exibicao' => 'auto_exibe_hora',
					'secao' => 'Horário',
					'ordem' => 7,
				),
				array('nome' => 'Local', 'campo_tabela' => 'local', 'type' => 'text', 'class' => ' gWidth', 'exb_listagem' => 1, 'secao' => 'Horário', 'ordem' => 8),
				array('nome' => 'Ordem', 'campo_tabela' => 'ordem', 'type' => 'text', 'exb_listagem' => 1, 'secao' => 'Publicação', 'ordem' => 9),
				array(
					'nome' => 'Destaque',
					'campo_tabela' => 'destaque',
					'type' => 'select',
					'valor' => 'Não,Sim',
					'exb_listagem' => 1,
					'secao' => 'Publicação',
					'ordem' => 10,
				),
				array(
					'nome' => 'Ativo no site',
					'campo_tabela' => 'ativo',
					'type' => 'select',
					'valor' => 'Não,Sim',
					'exb_listagem' => 1,
					'exb_filtro' => 1,
					'secao' => 'Publicação',
					'ordem' => 11,
				),
			),
		),
	),
);
