ServerName localhost

<Directory /var/www/html>
    Options FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

<Directory /var/www/html/dump>
    Require all denied
</Directory>

<FilesMatch "^\.">
    Require all denied
</FilesMatch>
